### ISSUE TITLE
How to change shortcut?

### ISSUE THREAD

**Issue by giorgoc** [writecodedrinkcoffee/sublime-cfdocs#1]
Any idea how to change the default shortcut from ctrl+shift+alt+/ into something else? let's say F1 ?

thanks!
George

**Comment by giorgoc** [comment]
Just answered myself! :-) To help you do this here's the command to be added to the user's key bindings.

`"keys": ["f1"], "command": "cf_docs_search_selection"`

**Comment by mikesprague** [comment]
Thanks for the feedback and glad you figured it out! I'm going to leave the default one as is since it is easy to change; f1 is usually mapped already and despite mine being an unusual combination, I couldn't find it overwritten by any other packages I used and the keys are in places that make it easy to use.

**Comment by giorgoc** [comment]
Yes i understand, although F1 for help, is the next top shortcut after of
course CTRL+C in an IDE :-)

**Comment by mikesprague** [comment]
For what it's worth, that's exactly why I don't want to override it with this package. F1 _should_ be help for the editor itself, not an individual package. It is most user's expectation when they hit f1 that it will open help for the software as opposed to an add-on (and this isn't a very widely used package). Glad you are finding the package useful :smile:

**Comment by giorgoc** [comment]
haha :-) totally understand! :-) thats the beauty of sublime though, highly
customisable :-)

thank you and keep on with the updates ;-)
